<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin 1.0
// Source: google/spanner/admin/database/v1/spanner_database_admin.proto
//   Date: 2016-09-19 21:10:57

namespace google\spanner\admin\database\v1 {

  class Database extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $name = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'google.spanner.admin.database.v1.Database');

      // OPTIONAL STRING name = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "name";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <name> has a value
     *
     * @return boolean
     */
    public function hasName(){
      return $this->_has(1);
    }
    
    /**
     * Clear <name> value
     *
     * @return \google\spanner\admin\database\v1\Database
     */
    public function clearName(){
      return $this->_clear(1);
    }
    
    /**
     * Get <name> value
     *
     * @return string
     */
    public function getName(){
      return $this->_get(1);
    }
    
    /**
     * Set <name> value
     *
     * @param string $value
     * @return \google\spanner\admin\database\v1\Database
     */
    public function setName( $value){
      return $this->_set(1, $value);
    }
  }
}

namespace google\spanner\admin\database\v1 {

  class ListDatabasesRequest extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $name = null;
    
    /**  @var int */
    public $page_size = null;
    
    /**  @var string */
    public $page_token = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'google.spanner.admin.database.v1.ListDatabasesRequest');

      // OPTIONAL STRING name = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "name";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL INT32 page_size = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "page_size";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING page_token = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "page_token";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <name> has a value
     *
     * @return boolean
     */
    public function hasName(){
      return $this->_has(1);
    }
    
    /**
     * Clear <name> value
     *
     * @return \google\spanner\admin\database\v1\ListDatabasesRequest
     */
    public function clearName(){
      return $this->_clear(1);
    }
    
    /**
     * Get <name> value
     *
     * @return string
     */
    public function getName(){
      return $this->_get(1);
    }
    
    /**
     * Set <name> value
     *
     * @param string $value
     * @return \google\spanner\admin\database\v1\ListDatabasesRequest
     */
    public function setName( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <page_size> has a value
     *
     * @return boolean
     */
    public function hasPageSize(){
      return $this->_has(3);
    }
    
    /**
     * Clear <page_size> value
     *
     * @return \google\spanner\admin\database\v1\ListDatabasesRequest
     */
    public function clearPageSize(){
      return $this->_clear(3);
    }
    
    /**
     * Get <page_size> value
     *
     * @return int
     */
    public function getPageSize(){
      return $this->_get(3);
    }
    
    /**
     * Set <page_size> value
     *
     * @param int $value
     * @return \google\spanner\admin\database\v1\ListDatabasesRequest
     */
    public function setPageSize( $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <page_token> has a value
     *
     * @return boolean
     */
    public function hasPageToken(){
      return $this->_has(4);
    }
    
    /**
     * Clear <page_token> value
     *
     * @return \google\spanner\admin\database\v1\ListDatabasesRequest
     */
    public function clearPageToken(){
      return $this->_clear(4);
    }
    
    /**
     * Get <page_token> value
     *
     * @return string
     */
    public function getPageToken(){
      return $this->_get(4);
    }
    
    /**
     * Set <page_token> value
     *
     * @param string $value
     * @return \google\spanner\admin\database\v1\ListDatabasesRequest
     */
    public function setPageToken( $value){
      return $this->_set(4, $value);
    }
  }
}

namespace google\spanner\admin\database\v1 {

  class ListDatabasesResponse extends \DrSlump\Protobuf\Message {

    /**  @var \google\spanner\admin\database\v1\Database[]  */
    public $databases = array();
    
    /**  @var string */
    public $next_page_token = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'google.spanner.admin.database.v1.ListDatabasesResponse');

      // REPEATED MESSAGE databases = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "databases";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\google\spanner\admin\database\v1\Database';
      $descriptor->addField($f);

      // OPTIONAL STRING next_page_token = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "next_page_token";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <databases> has a value
     *
     * @return boolean
     */
    public function hasDatabases(){
      return $this->_has(1);
    }
    
    /**
     * Clear <databases> value
     *
     * @return \google\spanner\admin\database\v1\ListDatabasesResponse
     */
    public function clearDatabases(){
      return $this->_clear(1);
    }
    
    /**
     * Get <databases> value
     *
     * @param int $idx
     * @return \google\spanner\admin\database\v1\Database
     */
    public function getDatabases($idx = NULL){
      return $this->_get(1, $idx);
    }
    
    /**
     * Set <databases> value
     *
     * @param \google\spanner\admin\database\v1\Database $value
     * @return \google\spanner\admin\database\v1\ListDatabasesResponse
     */
    public function setDatabases(\google\spanner\admin\database\v1\Database $value, $idx = NULL){
      return $this->_set(1, $value, $idx);
    }
    
    /**
     * Get all elements of <databases>
     *
     * @return \google\spanner\admin\database\v1\Database[]
     */
    public function getDatabasesList(){
     return $this->_get(1);
    }
    
    /**
     * Add a new element to <databases>
     *
     * @param \google\spanner\admin\database\v1\Database $value
     * @return \google\spanner\admin\database\v1\ListDatabasesResponse
     */
    public function addDatabases(\google\spanner\admin\database\v1\Database $value){
     return $this->_add(1, $value);
    }
    
    /**
     * Check if <next_page_token> has a value
     *
     * @return boolean
     */
    public function hasNextPageToken(){
      return $this->_has(2);
    }
    
    /**
     * Clear <next_page_token> value
     *
     * @return \google\spanner\admin\database\v1\ListDatabasesResponse
     */
    public function clearNextPageToken(){
      return $this->_clear(2);
    }
    
    /**
     * Get <next_page_token> value
     *
     * @return string
     */
    public function getNextPageToken(){
      return $this->_get(2);
    }
    
    /**
     * Set <next_page_token> value
     *
     * @param string $value
     * @return \google\spanner\admin\database\v1\ListDatabasesResponse
     */
    public function setNextPageToken( $value){
      return $this->_set(2, $value);
    }
  }
}

namespace google\spanner\admin\database\v1 {

  class CreateDatabaseRequest extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $name = null;
    
    /**  @var string */
    public $create_statement = null;
    
    /**  @var string[]  */
    public $extra_statements = array();
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'google.spanner.admin.database.v1.CreateDatabaseRequest');

      // OPTIONAL STRING name = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "name";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING create_statement = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "create_statement";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // REPEATED STRING extra_statements = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "extra_statements";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <name> has a value
     *
     * @return boolean
     */
    public function hasName(){
      return $this->_has(1);
    }
    
    /**
     * Clear <name> value
     *
     * @return \google\spanner\admin\database\v1\CreateDatabaseRequest
     */
    public function clearName(){
      return $this->_clear(1);
    }
    
    /**
     * Get <name> value
     *
     * @return string
     */
    public function getName(){
      return $this->_get(1);
    }
    
    /**
     * Set <name> value
     *
     * @param string $value
     * @return \google\spanner\admin\database\v1\CreateDatabaseRequest
     */
    public function setName( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <create_statement> has a value
     *
     * @return boolean
     */
    public function hasCreateStatement(){
      return $this->_has(2);
    }
    
    /**
     * Clear <create_statement> value
     *
     * @return \google\spanner\admin\database\v1\CreateDatabaseRequest
     */
    public function clearCreateStatement(){
      return $this->_clear(2);
    }
    
    /**
     * Get <create_statement> value
     *
     * @return string
     */
    public function getCreateStatement(){
      return $this->_get(2);
    }
    
    /**
     * Set <create_statement> value
     *
     * @param string $value
     * @return \google\spanner\admin\database\v1\CreateDatabaseRequest
     */
    public function setCreateStatement( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <extra_statements> has a value
     *
     * @return boolean
     */
    public function hasExtraStatements(){
      return $this->_has(3);
    }
    
    /**
     * Clear <extra_statements> value
     *
     * @return \google\spanner\admin\database\v1\CreateDatabaseRequest
     */
    public function clearExtraStatements(){
      return $this->_clear(3);
    }
    
    /**
     * Get <extra_statements> value
     *
     * @param int $idx
     * @return string
     */
    public function getExtraStatements($idx = NULL){
      return $this->_get(3, $idx);
    }
    
    /**
     * Set <extra_statements> value
     *
     * @param string $value
     * @return \google\spanner\admin\database\v1\CreateDatabaseRequest
     */
    public function setExtraStatements( $value, $idx = NULL){
      return $this->_set(3, $value, $idx);
    }
    
    /**
     * Get all elements of <extra_statements>
     *
     * @return string[]
     */
    public function getExtraStatementsList(){
     return $this->_get(3);
    }
    
    /**
     * Add a new element to <extra_statements>
     *
     * @param string $value
     * @return \google\spanner\admin\database\v1\CreateDatabaseRequest
     */
    public function addExtraStatements( $value){
     return $this->_add(3, $value);
    }
  }
}

namespace google\spanner\admin\database\v1 {

  class UpdateDatabaseRequest extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $database = null;
    
    /**  @var string[]  */
    public $statements = array();
    
    /**  @var string */
    public $operation_id = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'google.spanner.admin.database.v1.UpdateDatabaseRequest');

      // OPTIONAL STRING database = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "database";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // REPEATED STRING statements = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "statements";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $descriptor->addField($f);

      // OPTIONAL STRING operation_id = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "operation_id";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <database> has a value
     *
     * @return boolean
     */
    public function hasDatabase(){
      return $this->_has(1);
    }
    
    /**
     * Clear <database> value
     *
     * @return \google\spanner\admin\database\v1\UpdateDatabaseRequest
     */
    public function clearDatabase(){
      return $this->_clear(1);
    }
    
    /**
     * Get <database> value
     *
     * @return string
     */
    public function getDatabase(){
      return $this->_get(1);
    }
    
    /**
     * Set <database> value
     *
     * @param string $value
     * @return \google\spanner\admin\database\v1\UpdateDatabaseRequest
     */
    public function setDatabase( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <statements> has a value
     *
     * @return boolean
     */
    public function hasStatements(){
      return $this->_has(2);
    }
    
    /**
     * Clear <statements> value
     *
     * @return \google\spanner\admin\database\v1\UpdateDatabaseRequest
     */
    public function clearStatements(){
      return $this->_clear(2);
    }
    
    /**
     * Get <statements> value
     *
     * @param int $idx
     * @return string
     */
    public function getStatements($idx = NULL){
      return $this->_get(2, $idx);
    }
    
    /**
     * Set <statements> value
     *
     * @param string $value
     * @return \google\spanner\admin\database\v1\UpdateDatabaseRequest
     */
    public function setStatements( $value, $idx = NULL){
      return $this->_set(2, $value, $idx);
    }
    
    /**
     * Get all elements of <statements>
     *
     * @return string[]
     */
    public function getStatementsList(){
     return $this->_get(2);
    }
    
    /**
     * Add a new element to <statements>
     *
     * @param string $value
     * @return \google\spanner\admin\database\v1\UpdateDatabaseRequest
     */
    public function addStatements( $value){
     return $this->_add(2, $value);
    }
    
    /**
     * Check if <operation_id> has a value
     *
     * @return boolean
     */
    public function hasOperationId(){
      return $this->_has(3);
    }
    
    /**
     * Clear <operation_id> value
     *
     * @return \google\spanner\admin\database\v1\UpdateDatabaseRequest
     */
    public function clearOperationId(){
      return $this->_clear(3);
    }
    
    /**
     * Get <operation_id> value
     *
     * @return string
     */
    public function getOperationId(){
      return $this->_get(3);
    }
    
    /**
     * Set <operation_id> value
     *
     * @param string $value
     * @return \google\spanner\admin\database\v1\UpdateDatabaseRequest
     */
    public function setOperationId( $value){
      return $this->_set(3, $value);
    }
  }
}

namespace google\spanner\admin\database\v1 {

  class UpdateDatabaseMetadata extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $database = null;
    
    /**  @var string[]  */
    public $statements = array();
    
    /**  @var \google\protobuf\Timestamp[]  */
    public $commit_timestamps = array();
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'google.spanner.admin.database.v1.UpdateDatabaseMetadata');

      // OPTIONAL STRING database = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "database";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // REPEATED STRING statements = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "statements";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $descriptor->addField($f);

      // REPEATED MESSAGE commit_timestamps = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "commit_timestamps";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\google\protobuf\Timestamp';
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <database> has a value
     *
     * @return boolean
     */
    public function hasDatabase(){
      return $this->_has(1);
    }
    
    /**
     * Clear <database> value
     *
     * @return \google\spanner\admin\database\v1\UpdateDatabaseMetadata
     */
    public function clearDatabase(){
      return $this->_clear(1);
    }
    
    /**
     * Get <database> value
     *
     * @return string
     */
    public function getDatabase(){
      return $this->_get(1);
    }
    
    /**
     * Set <database> value
     *
     * @param string $value
     * @return \google\spanner\admin\database\v1\UpdateDatabaseMetadata
     */
    public function setDatabase( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <statements> has a value
     *
     * @return boolean
     */
    public function hasStatements(){
      return $this->_has(2);
    }
    
    /**
     * Clear <statements> value
     *
     * @return \google\spanner\admin\database\v1\UpdateDatabaseMetadata
     */
    public function clearStatements(){
      return $this->_clear(2);
    }
    
    /**
     * Get <statements> value
     *
     * @param int $idx
     * @return string
     */
    public function getStatements($idx = NULL){
      return $this->_get(2, $idx);
    }
    
    /**
     * Set <statements> value
     *
     * @param string $value
     * @return \google\spanner\admin\database\v1\UpdateDatabaseMetadata
     */
    public function setStatements( $value, $idx = NULL){
      return $this->_set(2, $value, $idx);
    }
    
    /**
     * Get all elements of <statements>
     *
     * @return string[]
     */
    public function getStatementsList(){
     return $this->_get(2);
    }
    
    /**
     * Add a new element to <statements>
     *
     * @param string $value
     * @return \google\spanner\admin\database\v1\UpdateDatabaseMetadata
     */
    public function addStatements( $value){
     return $this->_add(2, $value);
    }
    
    /**
     * Check if <commit_timestamps> has a value
     *
     * @return boolean
     */
    public function hasCommitTimestamps(){
      return $this->_has(3);
    }
    
    /**
     * Clear <commit_timestamps> value
     *
     * @return \google\spanner\admin\database\v1\UpdateDatabaseMetadata
     */
    public function clearCommitTimestamps(){
      return $this->_clear(3);
    }
    
    /**
     * Get <commit_timestamps> value
     *
     * @param int $idx
     * @return \google\protobuf\Timestamp
     */
    public function getCommitTimestamps($idx = NULL){
      return $this->_get(3, $idx);
    }
    
    /**
     * Set <commit_timestamps> value
     *
     * @param \google\protobuf\Timestamp $value
     * @return \google\spanner\admin\database\v1\UpdateDatabaseMetadata
     */
    public function setCommitTimestamps(\google\protobuf\Timestamp $value, $idx = NULL){
      return $this->_set(3, $value, $idx);
    }
    
    /**
     * Get all elements of <commit_timestamps>
     *
     * @return \google\protobuf\Timestamp[]
     */
    public function getCommitTimestampsList(){
     return $this->_get(3);
    }
    
    /**
     * Add a new element to <commit_timestamps>
     *
     * @param \google\protobuf\Timestamp $value
     * @return \google\spanner\admin\database\v1\UpdateDatabaseMetadata
     */
    public function addCommitTimestamps(\google\protobuf\Timestamp $value){
     return $this->_add(3, $value);
    }
  }
}

namespace google\spanner\admin\database\v1 {

  class DropDatabaseRequest extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $database = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'google.spanner.admin.database.v1.DropDatabaseRequest');

      // OPTIONAL STRING database = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "database";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <database> has a value
     *
     * @return boolean
     */
    public function hasDatabase(){
      return $this->_has(1);
    }
    
    /**
     * Clear <database> value
     *
     * @return \google\spanner\admin\database\v1\DropDatabaseRequest
     */
    public function clearDatabase(){
      return $this->_clear(1);
    }
    
    /**
     * Get <database> value
     *
     * @return string
     */
    public function getDatabase(){
      return $this->_get(1);
    }
    
    /**
     * Set <database> value
     *
     * @param string $value
     * @return \google\spanner\admin\database\v1\DropDatabaseRequest
     */
    public function setDatabase( $value){
      return $this->_set(1, $value);
    }
  }
}

namespace google\spanner\admin\database\v1 {

  class GetDatabaseDDLRequest extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $database = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'google.spanner.admin.database.v1.GetDatabaseDDLRequest');

      // OPTIONAL STRING database = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "database";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <database> has a value
     *
     * @return boolean
     */
    public function hasDatabase(){
      return $this->_has(1);
    }
    
    /**
     * Clear <database> value
     *
     * @return \google\spanner\admin\database\v1\GetDatabaseDDLRequest
     */
    public function clearDatabase(){
      return $this->_clear(1);
    }
    
    /**
     * Get <database> value
     *
     * @return string
     */
    public function getDatabase(){
      return $this->_get(1);
    }
    
    /**
     * Set <database> value
     *
     * @param string $value
     * @return \google\spanner\admin\database\v1\GetDatabaseDDLRequest
     */
    public function setDatabase( $value){
      return $this->_set(1, $value);
    }
  }
}

namespace google\spanner\admin\database\v1 {

  class GetDatabaseDDLResponse extends \DrSlump\Protobuf\Message {

    /**  @var string[]  */
    public $statements = array();
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'google.spanner.admin.database.v1.GetDatabaseDDLResponse');

      // REPEATED STRING statements = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "statements";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <statements> has a value
     *
     * @return boolean
     */
    public function hasStatements(){
      return $this->_has(1);
    }
    
    /**
     * Clear <statements> value
     *
     * @return \google\spanner\admin\database\v1\GetDatabaseDDLResponse
     */
    public function clearStatements(){
      return $this->_clear(1);
    }
    
    /**
     * Get <statements> value
     *
     * @param int $idx
     * @return string
     */
    public function getStatements($idx = NULL){
      return $this->_get(1, $idx);
    }
    
    /**
     * Set <statements> value
     *
     * @param string $value
     * @return \google\spanner\admin\database\v1\GetDatabaseDDLResponse
     */
    public function setStatements( $value, $idx = NULL){
      return $this->_set(1, $value, $idx);
    }
    
    /**
     * Get all elements of <statements>
     *
     * @return string[]
     */
    public function getStatementsList(){
     return $this->_get(1);
    }
    
    /**
     * Add a new element to <statements>
     *
     * @param string $value
     * @return \google\spanner\admin\database\v1\GetDatabaseDDLResponse
     */
    public function addStatements( $value){
     return $this->_add(1, $value);
    }
  }
}

namespace google\spanner\admin\database\v1 {

  class DatabaseAdminClient extends \Grpc\BaseStub {

    public function __construct($hostname, $opts) {
      parent::__construct($hostname, $opts);
    }
    /**
     * @param google\spanner\admin\database\v1\ListDatabasesRequest $input
     */
    public function ListDatabases(\google\spanner\admin\database\v1\ListDatabasesRequest $argument, $metadata = array(), $options = array()) {
      return $this->_simpleRequest('/google.spanner.admin.database.v1.DatabaseAdmin/ListDatabases', $argument, '\google\spanner\admin\database\v1\ListDatabasesResponse::deserialize', $metadata, $options);
    }
    /**
     * @param google\spanner\admin\database\v1\CreateDatabaseRequest $input
     */
    public function CreateDatabase(\google\spanner\admin\database\v1\CreateDatabaseRequest $argument, $metadata = array(), $options = array()) {
      return $this->_simpleRequest('/google.spanner.admin.database.v1.DatabaseAdmin/CreateDatabase', $argument, '\google\spanner\admin\database\v1\Database::deserialize', $metadata, $options);
    }
    /**
     * @param google\spanner\admin\database\v1\UpdateDatabaseRequest $input
     */
    public function UpdateDatabase(\google\spanner\admin\database\v1\UpdateDatabaseRequest $argument, $metadata = array(), $options = array()) {
      return $this->_simpleRequest('/google.spanner.admin.database.v1.DatabaseAdmin/UpdateDatabase', $argument, '\google\longrunning\Operation::deserialize', $metadata, $options);
    }
    /**
     * @param google\spanner\admin\database\v1\DropDatabaseRequest $input
     */
    public function DropDatabase(\google\spanner\admin\database\v1\DropDatabaseRequest $argument, $metadata = array(), $options = array()) {
      return $this->_simpleRequest('/google.spanner.admin.database.v1.DatabaseAdmin/DropDatabase', $argument, '\google\protobuf\EmptyC::deserialize', $metadata, $options);
    }
    /**
     * @param google\spanner\admin\database\v1\GetDatabaseDDLRequest $input
     */
    public function GetDatabaseDDL(\google\spanner\admin\database\v1\GetDatabaseDDLRequest $argument, $metadata = array(), $options = array()) {
      return $this->_simpleRequest('/google.spanner.admin.database.v1.DatabaseAdmin/GetDatabaseDDL', $argument, '\google\spanner\admin\database\v1\GetDatabaseDDLResponse::deserialize', $metadata, $options);
    }
    /**
     * @param google\iam\v1\SetIamPolicyRequest $input
     */
    public function SetIamPolicy(\google\iam\v1\SetIamPolicyRequest $argument, $metadata = array(), $options = array()) {
      return $this->_simpleRequest('/google.spanner.admin.database.v1.DatabaseAdmin/SetIamPolicy', $argument, '\google\iam\v1\Policy::deserialize', $metadata, $options);
    }
    /**
     * @param google\iam\v1\GetIamPolicyRequest $input
     */
    public function GetIamPolicy(\google\iam\v1\GetIamPolicyRequest $argument, $metadata = array(), $options = array()) {
      return $this->_simpleRequest('/google.spanner.admin.database.v1.DatabaseAdmin/GetIamPolicy', $argument, '\google\iam\v1\Policy::deserialize', $metadata, $options);
    }
    /**
     * @param google\iam\v1\TestIamPermissionsRequest $input
     */
    public function TestIamPermissions(\google\iam\v1\TestIamPermissionsRequest $argument, $metadata = array(), $options = array()) {
      return $this->_simpleRequest('/google.spanner.admin.database.v1.DatabaseAdmin/TestIamPermissions', $argument, '\google\iam\v1\TestIamPermissionsResponse::deserialize', $metadata, $options);
    }
  }
}
